:sourcedir: ./../../reactor-netty-core/src/main/java
:examplesdir: ./../../reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server
:javadoc: https://projectreactor.io/docs/netty/release/api

[[tcp-server]]
= TCP Server

`Reactor Netty` 提供易使用和配置的
{javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`]。
它隐藏了创建 `TCP` 服务所需的大部分 `Netty` 功能，并且增加了 `Reactive Streams` 背压。

== 启动和停止

为了启动一个 `TCP` 服务，你必须创建和配置一个 {javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`]  实例。
默认情况下，`host` 配置为任何本地地址，并在调用 `bind` 操作时，系统会选择一个临时端口。以下示例显示了如何创建和配置一个 `TcpServer` 实例：

====
[source,java,indent=0]
.{examplesdir}/create/Application.java
----
include::{examplesdir}/create/Application.java[lines=18..31]
----
<1> 创建一个配置就绪的 {javadoc}/reactor/netty/tcp/TcpServer.html[`TcpServer`] 实例。
<2> 以阻塞方式启动服务，并等待其完成初始化。
====

返回的 {javadoc}/reactor/netty/DisposableServer.html[`DisposableServer`] 提供一个简单的服务API，包括 {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`]，这将以阻塞的方式关闭服务。

=== Host和Port

要在特定的 `host` 和 `port` 上服务，你可以应用以下配置到 `TCP` 服务中：

====
[source,java,indent=0]
.{examplesdir}/address/Application.java
----
include::{examplesdir}/address/Application.java[lines=18..33]
----
<1> 配置 `TCP` 服务 host
<2> 配置 `TCP` 服务 port
====

== 写数据

为了发送数据到连接的客户端，你必须连接一个I/O处理器。
这个I/O处理器可以访问 {javadoc}/reactor/netty/NettyOutbound.html[`NettyOutbound`] 来写入数据。以下示例显示了如何连接一个I/O处理器：

====
[source,java,indent=0]
.{examplesdir}/send/Application.java
----
include::{examplesdir}/send/Application.java[lines=18..33]
----
<1> 发送 `hello` 字符到连接的客户端
====

== 消费数据

为了从连接的客户端的接收数据，你必须连接一个I/O处理器。
这个I/O处理器可以访问 {javadoc}/reactor/netty/NettyInbound.html[`NettyInbound`] 来读取数据。以下示例显示了如何使用：

====
[source,java,indent=0]
.{examplesdir}/read/Application.java
----
include::{examplesdir}/read/Application.java[lines=18..32]
----
<1> 从连接的客户端接收数据
====

== 生命周期回调

提供以下生命周期的回调，让你能够扩展 `TCP` 服务：

* `doOnBind`: 当服务channel将要绑定时被调用。
* `doOnBound`: 当服务channel绑定时被调用。
* `doOnConnection`: 当远程客户端连接时被调用。
* `doOnUnbound`: 当服务channel解除绑定时被调用。

以下示例使用 `doOnConnection` 回调：

====
[source,java,indent=0]
.{examplesdir}/lifecycle/Application.java
----
include::{examplesdir}/lifecycle/Application.java[lines=18..35]
----
<1> 当远程客户端连接时，使用 `ReadTimeoutHandler` 扩展 `Netty` 管道。
====

== TCP级的配置

本节介绍了三种可以在TCP级使用的配置：

* <<server-tcp-level-configurations-channel-options>>
* <<server-tcp-level-configurations-event-wire-logger>>
* <<server-tcp-level-configurations-event-loop-group>>

[[server-tcp-level-configurations-channel-options]]
=== 设置Channel选项

默认情况下，`TCP` 服务使用以下配置：

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/tcp/TcpServerBind.java
----
include::{sourcedir}/reactor/netty/tcp/TcpServerBind.java[lines=40..48]
----
====

如果需要其他的选项或者更改当前选项，则可以使用以下配置：

====
[source,java,indent=0]
.{examplesdir}/channeloptions/Application.java
----
include::{examplesdir}/channeloptions/Application.java[lines=18..33]
----
====

你可以在下面的链接中找到更多关于 `Netty` channel选项：

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[server-tcp-level-configurations-event-wire-logger]]
=== Wire Logger

Reactor Netty提供了wire logging用于检测节点之间的流量。
默认情况下，wire logging未启用。
为了启用它，你必须设置 `reactor.netty.tcp.TcpServer` 日志级别为 `DEBUG` 且使用以下配置；

====
[source,java,indent=0]
.{examplesdir}/wiretap/Application.java
----
include::{examplesdir}/wiretap/Application.java[lines=18..32]
----
<1> 启用wire logging
====

[[server-tcp-level-configurations-event-loop-group]]
=== Event Loop Group

默认情况下，`TCP` 服务使用 "`Event Loop Group`" ，其中工作线程数等于初始化时运行可用的处理器（最小值为4）数量。当你需要其他配置时，你可以使用 {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create` 方法之一。

`Event Loop Group` 的默认配置如下：

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=79..108]
----
====

如果需要更改这些配置，则可使用以下配置：

====
[source,java,indent=0]
.{examplesdir}/eventloop/Application.java
----
include::{examplesdir}/eventloop/Application.java[lines=18..35]
----
====

== SSL和TLS

当你需要SSL或TLS，你可以使用下面所示的配置：
默认情况下，如果 `OpenSSL` 是可用的，
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#OPENSSL[`SslProvider.OPENSSL`]
将作为一个provider。否则会使用
https://netty.io/4.1/api/io/netty/handler/ssl/SslProvider.html#JDK[`SslProvider.JDK`]。
通过 https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#sslProvider-io.netty.handler.ssl.SslProvider-[`SslContextBuilder`]
或设置 `-Dio.netty.handler.ssl.noOpenSsl=true` 来切换provider。

以下示例为使用 `SslContextBuilder`：

====
[source,java,indent=0]
.{examplesdir}/security/Application.java
----
include::{examplesdir}/security/Application.java[lines=18..39]
----
====

=== 服务名称指示
你可以配置 `TCP` 服务与多个 `SslContext` 映射到一个特定的域名。
配置 `SNI` 映射时，可以使用一个确切的或包含通配符的域名。

以下示例使用了一个包含通配符的域名：

====
[source,java,indent=0]
.{examplesdir}/sni/Application.java
----
include::{examplesdir}/sni/Application.java[lines=18..47]
----
====

== 指标
TCP服务内置集成了 https://micrometer.io/[`Micrometer`]。
它会暴露所有以 `reactor.netty.tcp.server` 开头的指标。

下表提供了TCP服务指标的信息：

[width="100%",options="header"]
|=======
| 指标名称 | 类型 | 描述
| reactor.netty.tcp.server.data.received | DistributionSummary | 收到的数据量，以字节为单位
| reactor.netty.tcp.server.data.sent | DistributionSummary | 发送的数据量，以字节为单位
| reactor.netty.tcp.server.errors | Counter | 错误发生的数量
| reactor.netty.tcp.server.tls.handshake.time | Timer | TLS握手花费的时间
|=======

额外的其他指标：

include::alloc-metrics.adoc[]

以下示例启用了该集成：

====
[source,java,indent=0]
.{examplesdir}/metrics/Application.java
----
include::{examplesdir}/metrics/Application.java[lines=18..32]
----
<1> 启用内置集成的Micrometer
====

当TCP服务指标需要与 `Micrometer` 以外的系统集成或自己与 `Micrometer` 集成时，你可以提供自己的指标记录器，如下所示：

====
[source,java,indent=0]
.{examplesdir}/metrics/custom/Application.java
----
include::{examplesdir}/metrics/custom/Application.java[lines=18..35]
----
<1> 启用TCP服务指标并且提供 {javadoc}/reactor/netty/channel/ChannelMetricsRecorder.html[`ChannelMetricsRecorder`] 实现。
====

== 进程间通信（Unix Domain Sockets）
`TCP` 服务在使用本地传输时支持Unix Domain Sockets (UDS)。

以下示例显示了如何使用UDS支持：

====
[source,java,indent=0]
.{examplesdir}/uds/Application.java
----
include::{examplesdir}/uds/Application.java[lines=18..33]
----
<1> 指定要使用的 `DomainSocketAddress`
====
