:sourcedir: ./../../reactor-netty-core/src/main/java
:examplesdir: ./../../reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/client
:javadoc: https://projectreactor.io/docs/netty/release/api

[[udp-client]]
= UDP Client

Reactor Netty提供易使用和配置的
{javadoc}/reactor/netty/udp/UdpClient.html[`UdpClient`]。
它隐藏了创建 `UDP` 客户端所需的大部分 `Netty` 功能，并且增加了 `Reactive Streams` 背压。

== 连接和断开

要使用UDP客户端连接到指定端点，必须创建和配置一个
{javadoc}/reactor/netty/udp/UdpClient.html[UdpClient] 实例。
默认情况下，host配置为 `localhost`，port为 `12012`。
以下示例显示了如何创建和连接一个UDP客户端：

====
[source,java,indent=0]
.{examplesdir}/create/Application.java
----
include::{examplesdir}/create/Application.java[lines=18..32]
----
<1> 创建一个配置就绪的 {javadoc}/reactor/netty/udp/UdpClient.html[`UdpClient`] 实例。
<2> 以阻塞方式建立客户端连接，并等待其完成初始化。
====

返回的 {javadoc}/reactor/netty/Connection.html[`Connection`] 提供一个简单的连接API，包括 {javadoc}/reactor/netty/DisposableChannel.html#disposeNow-java.time.Duration-[`disposeNow()`]，
这将以阻塞的方式关闭客户端。

=== Host和Port

为了连接到特定到 `host` 和 `port`，可对 `UDP` 客户端使用以下配置：

====
[source,java,indent=0]
.{examplesdir}/address/Application.java
----
include::{examplesdir}/address/Application.java[lines=18..34]
----
<1> 配置客户端应该连接的 `host`
<2> 配置客户端应该连接的 `port`
====

== 写数据

为了发送数据到指定节点，需要连接一个I/O处理器。
这个I/O处理器可以访问 {javadoc}/reactor/netty/udp/UdpOutbound.html[`UdpOutbound`] 来写入数据。

以下示例显示如何发送 `hello`：

====
[source,java,indent=0]
.{examplesdir}/send/Application.java
----
include::{examplesdir}/send/Application.java[lines=18..37]
----
<1> 发送 `hello` 字符串到远程节点。
====

== 消费数据

为了从指定节点接收数据，必须连接一个I/O处理器。
这个I/O处理器可以访问 {javadoc}/reactor/netty/udp/UdpInbound.html[`UdpInbound`] 来读取数据。
以下示例显示如何消费数据：

====
[source,java,indent=0]
.{examplesdir}/read/Application.java
----
include::{examplesdir}/read/Application.java[lines=18..35]
----
<1> 从指定节点接收数据
====

== 生命周期回调

提供下列生命周期回调能够扩展 `UDP` 客户端：

* `doOnConnect`: 当channel将要连接时被调用。
* `doOnConnected`: 当channel连接时被调用。
* `doOnDisconnected`: 当channel连接断开时被调用。

下面的例子使用 `doOnConnected` 方法：

====
[source,java,indent=0]
.{examplesdir}/lifecycle/Application.java
----
include::{examplesdir}/lifecycle/Application.java[lines=18..36]
----
<1> 当channel连接时，使用 `LineBasedFrameDecoder` 扩展Netty管道。
====

== 连接配置

本节描述三类可用在UDP层的配置：

* <<client-udp-connection-configurations-channel-options>>
* <<client-udp-connection-configurations-wire-logger>>
* <<client-udp-connection-configurations-event-loop-group>>

[[client-udp-connection-configurations-channel-options]]
=== Channel选项

默认情况下，`UDP` 客户端使用以下配置选项：

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/udp/UdpClientConnect.java
----
include::{sourcedir}/reactor/netty/udp/UdpClientConnect.java[lines=37..42]
----
====

如果需要额外的选项或修改当前选项，则可以使用以下配置：

====
[source,java,indent=0]
.{examplesdir}/channeloptions/Application.java
----
include::{examplesdir}/channeloptions/Application.java[lines=18..36]
----
====

你可以在下面的链接中找到更多关于 `Netty` channel选项：

* https://netty.io/4.1/api/io/netty/channel/ChannelOption.html[`ChannelOption`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/net/socketOpt.html[Socket Options]

[[client-udp-connection-configurations-wire-logger]]
=== Wire Logger

Reactor Netty提供了wire logging用于检测节点之间的流量。
默认情况下，wire logging未启用。
为了启用它，你必须设置 `reactor.netty.udp.UdpClient` 日志级别为 `DEBUG` 且使用以下配置：

====
[source,java,indent=0]
.{examplesdir}/wiretap/Application.java
----
include::{examplesdir}/wiretap/Application.java[lines=18..35]
----
<1> 启用wire logging
====

[[client-udp-connection-configurations-event-loop-group]]
=== Event Loop Group

默认情况下，`TCP` 客户端使用 "`Event Loop Group`"，其中工作线程数等于初始化时运行可用的处理器（最小值为4）数量。当你需要其他配置时，你可以使用 {javadoc}/reactor/netty/resources/LoopResources.html[LoopResource]`#create` 方法之一。

“`Event Loop Group`” 的默认配置如下：

====
[source,java,indent=0]
.{sourcedir}/reactor/netty/ReactorNetty.java
----
include::{sourcedir}/reactor/netty/ReactorNetty.java[lines=79..108]
----
====

如果需要更改这些配置，可以使用以下配置：

====
[source,java,indent=0]
.{examplesdir}/eventloop/Application.java
----
include::{examplesdir}/eventloop/Application.java[lines=18..38]
----
====

== 指标
UDP客户端内置集成了 https://micrometer.io/[`Micrometer`]。
它会暴露所有以 `reactor.netty.udp.client` 开头的指标。

下表提供了UDP客户端指标的信息：

[width="100%",options="header"]
|=======
| 指标名称 | 类别 | 描述
| reactor.netty.udp.client.data.received | DistributionSummary | 接收的数据量，以字节为单位
| reactor.netty.udp.client.data.sent | DistributionSummary | 发送的数据量，以字节为单位
| reactor.netty.udp.client.errors | Counter | 错误发生的数量
| reactor.netty.udp.client.connect.time | Timer | 连接到远程地址花费的时间
| reactor.netty.udp.client.address.resolver | Timer | 解析地址花费的时间
|=======

额外的其他指标：

include::alloc-metrics.adoc[]

以下示例启用了该集成：

====
[source,java,indent=0]
.{examplesdir}/metrics/Application.java
----
include::{examplesdir}/metrics/Application.java[lines=18..36]
----
<1> 启用内置集成的Micrometer
====

当UDP客户端指标需要与 `Micrometer` 以外的系统集成或自己与 `Micrometer` 集成时，你可以提供自己的指标记录器，如下所示：

====
[source,java,indent=0]
.{examplesdir}/metrics/custom/Application.java
----
include::{examplesdir}/metrics/custom/Application.java[lines=18..37]
----
<1> 启用UDP客户端指标并且提供 {javadoc}/reactor/netty/channel/ChannelMetricsRecorder.html[`ChannelMetricsRecorder`] 实现.
====
